spring:
  application:
    name: backend-oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: Ora1234
    driver-class-name: oracle.jdbc.OracleDriver
server:
  servlet:
    encoding:
      charset: UTF-8